### ISSUE TITLE
How do I reference variables exported from a Scss file?

### ISSUE THREAD

**Issue by ashikahmed3230** [ANONYMOUS-U7P4L/MY-OPEN-FILES#7]
I used the export method in cli and found that this method did not work on vite.

//index.scss

$--color-primary: #75126d;

:export {
  theme: $--color-primary;
}

import color from './index.scss'

console.log(color); 

/**log

@charset "UTF-8";

:export {
  theme: #75126d;
}
**/

In theory, an object should be returned.

**Comment by U7P4L-IN** [comment]
There's no such convention in vite.
